INSERT INTO users (USER_ID, USERNAME, PASSWORD, ENABLED) VALUES (1, 'peter', '1234', TRUE);
INSERT INTO users (USER_ID, USERNAME, PASSWORD, ENABLED) VALUES (2, 'raul', '1234', TRUE);
INSERT INTO users (USER_ID, USERNAME, PASSWORD, ENABLED) VALUES (3, 'yeray', '0000', FALSE);

INSERT INTO user_roles (USER_ROLE_ID, USER_ID,AUTHORITY) VALUES (1, 1, 'ROLE_USER');
INSERT INTO user_roles (USER_ROLE_ID, USER_ID,AUTHORITY) VALUES (2, 2, 'ROLE_USER');
INSERT INTO user_roles (USER_ROLE_ID, USER_ID,AUTHORITY) VALUES (3, 3, 'ROLE_USER');